services:
  # --- Messaging Infrastructure ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    networks:
      - social_media_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    networks:
      - social_media_net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "variant-scheduling-topic:1:1,variant-immediate-publish-topic:1:1,social-account-created-topic:1:1"

  # --- Databases ---
  post-db:
    image: postgres:15
    container_name: post-db
    environment:
      - POSTGRES_USER=admin1
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=post_service_db
    ports:
      - "5000:5432"
    volumes:
      - post-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin1 -d post_service_db"]

  scheduler-db:
    image: postgres:15
    container_name: scheduler-db
    environment:
      - POSTGRES_USER=admin2
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scheduler_service_db
    ports:
      - "5001:5432"
    volumes:
      - scheduler-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin2 -d scheduler_service_db"]

  social-account-db:
    image: postgres:15
    container_name: social-account-db
    environment:
      - POSTGRES_USER=admin3
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=social_account_service_db
    ports:
      - "5002:5432"
    volumes:
      - social-account-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin3 -d social_account_service_db" ]

  analytics-db:
    image: postgres:15
    container_name: analytics-db
    environment:
      - POSTGRES_USER=admin4
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=analytics-service-db
    ports:
      - "5003:5432"
    volumes:
      - analytics-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin4 -d analytics-service-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Application Services ---
  post-service:
    build: ./post-service
    container_name: post-service
    depends_on:
      post-db:
        condition: service_healthy
      kafka:
        condition: service_started
      social-account-service: { condition: service_started }
      analytics-service: { condition: service_started }

    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://post-db:5432/post_service_db
      - SPRING_DATASOURCE_USERNAME=admin1
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_URL=kafka:29092
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
      - CLIENTS_ANALYTICS_SERVICE_URL=http://analytics-service:8080
    networks:
      - social_media_net

  scheduler-service:
    build: ./scheduler-service
    container_name: scheduler-service
    depends_on:
      scheduler-db:
        condition: service_healthy
      kafka:
        condition: service_started
      social-account-service: { condition: service_started }
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://scheduler-db:5432/scheduler_service_db
      - SPRING_DATASOURCE_USERNAME=admin2
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_URL=kafka:29092
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
      - KAFKA_CLIENTID=scheduler-consumer-docker-1
      - SPRING_JMX_ENABLED=false
    networks:
      - social_media_net

  social-account-service:
    build: ./social-account-service
    container_name: social-account-service
    depends_on:
      social-account-db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://social-account-db:5432/social_account_service_db
      - SPRING_DATASOURCE_USERNAME=admin3
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - social_media_net

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    depends_on:
      analytics-db:
        condition: service_healthy
      kafka:
        condition: service_started
      social-account-service:
        condition: service_started
    ports:
      - "8083:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://analytics-db:5432/analytics-service-db
      - SPRING_DATASOURCE_USERNAME=admin4
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_URL=kafka:29092
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
    networks:
      - social_media_net

#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    container_name: keycloak
#    command: start-dev
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - KC_DB=postgres
#      - KC_DB_URL_HOST=keycloak-db
#      - KC_DB_USERNAME=keycloak
#      - KC_DB_PASSWORD=password
#      - KC_DB_SCHEMA=public
#    ports:
#      - "8088:8080"
#    depends_on:
#      - keycloak-db
#    restart: unless-stopped
#
#  keycloak-db:
#    image: postgres:13
#    container_name: keycloak-db
#    environment:
#      - POSTGRES_DB=keycloak
#      - POSTGRES_USER=keycloak
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - keycloak_db_data:/var/lib/postgresql/data
#    restart: unless-stopped

volumes:
  post-data:
  scheduler-data:
  social-account-data:
  analytics-data:
#  keycloak_db_data:

networks:
  social_media_net:
    driver: bridge