services:
  # --- Messaging Infrastructure ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    networks:
      - social_media_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    networks:
      - social_media_net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "variant-scheduling-topic:1:1,variant-immediate-publish-topic:1:1"

  # --- Databases ---
  post-db:
    image: postgres:15
    container_name: post-db
    environment:
      - POSTGRES_USER=admin1
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=post_service_db
    ports:
      - "5000:5432"
    volumes:
      - post-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin1 -d post_service_db"]

  scheduler-db:
    image: postgres:15
    container_name: scheduler-db
    environment:
      - POSTGRES_USER=admin2
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scheduler_service_db
    ports:
      - "5001:5432"
    volumes:
      - scheduler-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin2 -d scheduler_service_db"]

  social-account-db:
    image: postgres:15
    container_name: social-account-db
    environment:
      - POSTGRES_USER=admin3
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=social_account_service_db
    ports:
      - "5002:5432"
    volumes:
      - social-account-data:/var/lib/postgresql/data
    networks:
      - social_media_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin3 -d social_account_service_db" ]

  # --- Application Services ---
  post-service:
    build: ./post-service
    container_name: post-service
    depends_on:
      post-db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://post-db:5432/post_service_db
      - SPRING_DATASOURCE_USERNAME=admin1
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_URL=kafka:29092
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
    networks:
      - social_media_net

  scheduler-service:
    build: ./scheduler-service
    container_name: scheduler-service
    depends_on:
      scheduler-db:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://scheduler-db:5432/scheduler_service_db
      - SPRING_DATASOURCE_USERNAME=admin2
      - SPRING_DATASOURCE_PASSWORD=password
      - KAFKA_URL=kafka:29092
      - CLIENTS_SOCIAL_ACCOUNT_SERVICE_URL=http://social-account-service:8080
      - KAFKA_CLIENTID=scheduler-consumer-docker-1
    networks:
      - social_media_net

  social-account-service:
    build: ./social-account-service
    container_name: social-account-service
    depends_on:
      social-account-db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://social-account-db:5432/social_account_service_db
      - SPRING_DATASOURCE_USERNAME=admin3
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - social_media_net

volumes:
  post-data:
  scheduler-data:
  social-account-data:

networks:
  social_media_net:
    driver: bridge